title: "Lưu Văn Tuấn"
email: your-email@example.com
description: "Blog cá nhân"
baseurl: ""
url: "https://luuvantuan.github.io"
theme: minima
permalink: /:categories/:year/:month/:day/:title.html
plugins:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
